services:
  app1:
    build: .
    container_name: rinha-backend-2025-app1
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    volumes:
      - .:/usr/src/app
    command: npm start
    networks:
      - backend

  app2:
    build: .
    container_name: rinha-backend-2025-app2
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    volumes:
      - .:/usr/src/app
    command: npm start
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true