services:
  app:
    build: .
    container_name: rinha-backend-2025
    ports:
      - "9999:9999"
    deploy:
    resources:
      limits:
        cpus: "1.5"
        memory: "350MB"
    environment:
      - NODE_ENV=production
      - PORT=9999
    volumes:
      - .:/usr/src/app
    command: npm start